export type Claim = {
  patient_id: string
  patient_name: string
  billing_code: string
  amount: number
  insurance_provider: string
  payment_status: "Pending" | "Approved" | "Denied"
  claim_date: string
}

export const mockClaims: Claim[] = [
  {
    patient_id: "P1",
    patient_name: "John Smith",
    billing_code: "B1001",
    amount: 1675.5,
    insurance_provider: "Blue Shield",
    payment_status: "Pending",
    claim_date: "2025-03-25",
  },
  {
    patient_id: "P2",
    patient_name: "Sarah Johnson",
    billing_code: "B2002",
    amount: 2310.09,
    insurance_provider: "Medicare",
    payment_status: "Approved",
    claim_date: "2025-01-05",
  },
  {
    patient_id: "P3",
    patient_name: "Robert Chen",
    billing_code: "B3003",
    amount: 4945.57,
    insurance_provider: "Aetna",
    payment_status: "Pending",
    claim_date: "2025-03-04",
  },
  {
    patient_id: "P4",
    patient_name: "Lisa Williams",
    billing_code: "B4004",
    amount: 8338.89,
    insurance_provider: "UnitedHealth",
    payment_status: "Denied",
    claim_date: "2025-03-20",
  },
  {
    patient_id: "P5",
    patient_name: "Michael Garcia",
    billing_code: "B5005",
    amount: 3220.05,
    insurance_provider: "Cigna",
    payment_status: "Denied",
    claim_date: "2025-02-21",
  },
]

// Add more mock data for a more realistic dataset
export const extendedMockClaims: Claim[] = [
  ...mockClaims,
  {
    patient_id: "P6",
    patient_name: "Emily Rodriguez",
    billing_code: "B6006",
    amount: 1250.75,
    insurance_provider: "Blue Shield",
    payment_status: "Approved",
    claim_date: "2025-03-15",
  },
  {
    patient_id: "P7",
    patient_name: "David Kim",
    billing_code: "B7007",
    amount: 3750.25,
    insurance_provider: "Medicare",
    payment_status: "Pending",
    claim_date: "2025-02-28",
  },
  {
    patient_id: "P8",
    patient_name: "Jennifer Lee",
    billing_code: "B8008",
    amount: 5125.5,
    insurance_provider: "Aetna",
    payment_status: "Approved",
    claim_date: "2025-01-22",
  },
  {
    patient_id: "P9",
    patient_name: "Thomas Brown",
    billing_code: "B9009",
    amount: 2875.3,
    insurance_provider: "UnitedHealth",
    payment_status: "Denied",
    claim_date: "2025-03-10",
  },
  {
    patient_id: "P10",
    patient_name: "Maria Martinez",
    billing_code: "B1010",
    amount: 4225.8,
    insurance_provider: "Cigna",
    payment_status: "Pending",
    claim_date: "2025-02-15",
  },
  {
    patient_id: "P11",
    patient_name: "James Wilson",
    billing_code: "B1011",
    amount: 1875.45,
    insurance_provider: "Blue Shield",
    payment_status: "Approved",
    claim_date: "2025-01-30",
  },
  {
    patient_id: "P12",
    patient_name: "Patricia Taylor",
    billing_code: "B1012",
    amount: 6350.2,
    insurance_provider: "Medicare",
    payment_status: "Denied",
    claim_date: "2025-03-05",
  },
  // Adding more claims for pagination
  {
    patient_id: "P13",
    patient_name: "Kevin Patel",
    billing_code: "B1013",
    amount: 2145.75,
    insurance_provider: "Aetna",
    payment_status: "Pending",
    claim_date: "2025-02-10",
  },
  {
    patient_id: "P14",
    patient_name: "Olivia Thompson",
    billing_code: "B1014",
    amount: 3890.5,
    insurance_provider: "Blue Shield",
    payment_status: "Approved",
    claim_date: "2025-01-15",
  },
  {
    patient_id: "P15",
    patient_name: "Daniel Martinez",
    billing_code: "B1015",
    amount: 1750.25,
    insurance_provider: "Medicare",
    payment_status: "Denied",
    claim_date: "2025-03-18",
  },
  {
    patient_id: "P16",
    patient_name: "Sophia Lee",
    billing_code: "B1016",
    amount: 5275.8,
    insurance_provider: "UnitedHealth",
    payment_status: "Pending",
    claim_date: "2025-02-25",
  },
  {
    patient_id: "P17",
    patient_name: "William Johnson",
    billing_code: "B1017",
    amount: 4125.6,
    insurance_provider: "Cigna",
    payment_status: "Approved",
    claim_date: "2025-01-20",
  },
  {
    patient_id: "P18",
    patient_name: "Emma Davis",
    billing_code: "B1018",
    amount: 2950.4,
    insurance_provider: "Aetna",
    payment_status: "Denied",
    claim_date: "2025-03-12",
  },
  {
    patient_id: "P19",
    patient_name: "Alexander Wilson",
    billing_code: "B1019",
    amount: 6780.3,
    insurance_provider: "Medicare",
    payment_status: "Pending",
    claim_date: "2025-02-08",
  },
  {
    patient_id: "P20",
    patient_name: "Isabella Garcia",
    billing_code: "B1020",
    amount: 3450.9,
    insurance_provider: "Blue Shield",
    payment_status: "Approved",
    claim_date: "2025-01-25",
  },
  {
    patient_id: "P21",
    patient_name: "Ethan Brown",
    billing_code: "B1021",
    amount: 1980.7,
    insurance_provider: "UnitedHealth",
    payment_status: "Denied",
    claim_date: "2025-03-22",
  },
  {
    patient_id: "P22",
    patient_name: "Mia Rodriguez",
    billing_code: "B1022",
    amount: 5840.25,
    insurance_provider: "Cigna",
    payment_status: "Pending",
    claim_date: "2025-02-18",
  },
  {
    patient_id: "P23",
    patient_name: "Benjamin Taylor",
    billing_code: "B1023",
    amount: 4320.15,
    insurance_provider: "Aetna",
    payment_status: "Approved",
    claim_date: "2025-01-10",
  },
  {
    patient_id: "P24",
    patient_name: "Charlotte Martinez",
    billing_code: "B1024",
    amount: 2760.8,
    insurance_provider: "Medicare",
    payment_status: "Denied",
    claim_date: "2025-03-08",
  },
  {
    patient_id: "P25",
    patient_name: "Jacob Anderson",
    billing_code: "B1025",
    amount: 7150.45,
    insurance_provider: "Blue Shield",
    payment_status: "Pending",
    claim_date: "2025-02-22",
  },
  {
    patient_id: "P26",
    patient_name: "Amelia Thomas",
    billing_code: "B1026",
    amount: 3680.3,
    insurance_provider: "UnitedHealth",
    payment_status: "Approved",
    claim_date: "2025-01-18",
  },
  {
    patient_id: "P27",
    patient_name: "Michael Wilson",
    billing_code: "B1027",
    amount: 2140.9,
    insurance_provider: "Cigna",
    payment_status: "Denied",
    claim_date: "2025-03-14",
  },
  {
    patient_id: "P28",
    patient_name: "Abigail Harris",
    billing_code: "B1028",
    amount: 6290.75,
    insurance_provider: "Aetna",
    payment_status: "Pending",
    claim_date: "2025-02-05",
  },
  {
    patient_id: "P29",
    patient_name: "Matthew Clark",
    billing_code: "B1029",
    amount: 4570.6,
    insurance_provider: "Medicare",
    payment_status: "Approved",
    claim_date: "2025-01-28",
  },
  {
    patient_id: "P30",
    patient_name: "Emily Lewis",
    billing_code: "B1030",
    amount: 3120.4,
    insurance_provider: "Blue Shield",
    payment_status: "Denied",
    claim_date: "2025-03-01",
  },
]
